---
- name: Use elevate to migrate a centos7 host to rocky8
  hosts: all
  gather_facts: false
  become: true
  vars:
  
  tasks:
  - name: quick check if all hosts was specified with no limit
    ansible.builtin.assert:
      that: ansible_play_hosts_all|length < groups.all|length
      fail_msg: '[ERROR] All hosts not allowed.'
    run_once: true

  - name: Update current centos7 packages
    ansible.builtin.yum: 
      name: '*'
      state: latest
    register: cent_update

  - name: Reboot if updates were made
    ansible.builtin.reboot:
      reboot_timeout: 3600
    when: cent_update.changed

  - name: Install elevate package
    ansible.builtin.shell: yum install -y http://repo.almalinux.org/elevate/elevate-release-latest-el$(rpm --eval %rhel).noarch.rpm

  - name: Install leap packages for general and rocky
    ansible.builtin.yum:
      name:
        - leapp-upgrade
        - leapp-data-rocky
      state: latest

  - name: run the leapp preupgrade
    ansible.builtin.shell: leapp preupgrade
    register: leapp_preupgrade

  - name: Build fix command list based on preupgrade file
    ansible.builtin.shell: cat /var/log/leapp/leapp-report.txt | grep -F [command] | awk '{$1= ""; print $0}'
    register: fix_commands

  - name: Run standard fixes
    ansible.builtin.shell: "{{ item }}"
    loop: 
      - rmmod pata_acpi
      - echo PermitRootLogin yes | sudo tee -a /etc/ssh/sshd_config
      - leapp answer --section remove_pam_pkcs11_module_check.confirm=True

  - name: Run gathered fixes
    ansible.builtin.shell: "{{ item }}"
    loop: "{{ fix_commands.stdout_lines }}"

  - name: Run the leapp upgrade
    ansible.builtin.shell: leapp upgrade

  - name: Reboot to complete upgrade
    ansible.builtin.reboot:
      reboot_timeout: 3600
